AllCops:
  TargetRubyVersion: 2.3
Layout/ExtraSpacing:
  Exclude:
    - "**/*.gemspec"
Layout/SpaceAroundOperators:
  Exclude:
    - "**/*.gemspec"
Lint/HandleExceptions:
  AllowComments: true
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Max: 500
Metrics/LineLength:
  Max: 120
  Exclude:
    - "**/*_spec.rb"
Metrics/MethodLength:
  Max: 100
Metrics/ParameterLists:
  Max: 10
  CountKeywordArgs: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/BlockLength:
  Max: 100
  Exclude:
    - "**/*.gemspec"
    - "**/*_spec.rb"
Naming/PredicateName:
  NamePrefix: ["is_"]
  NamePrefixBlacklist: ["is_"]
Style/AndOr:
  EnforcedStyle: conditionals
Style/AsciiComments:
  Enabled: false
