language: ruby
rvm:
  - 2.3.0
  - 2.4.0
  - 2.5.0
  - 2.6.0
  - jruby-9.1.17.0
  - jruby-9.2.0.0
  - jruby-9.2.1.0
  - jruby-9.2.2.0
  - jruby-9.2.3.0
  - jruby-9.2.4.0
  - jruby-9.2.5.0
  - jruby-9.2.6.0
  - jruby-9.2.7.0
before_install:
  - gem update --system
  - gem install bundler
script:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; bundle exec rspec -f d -b; fi
  - bundle exec rubocop -f c --fail-level A
