language: ruby
rvm:
  - 2.3.0
  - 2.6.0
  - jruby-9.1.17.0
  - jruby-9.2.7.0
jdk:
  - openjdk8
before_install:
  - sudo apt-get install -y sqlite3 build-essential
  - gem update --system
  - gem install bundler
script:
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]
    then
      bundle exec rspec -f d -b
    fi
  - |
    if [ "$(ruby -e 'puts RUBY_PLATFORM')" != "java" ]
    then
      bundle exec rubocop -f c --fail-level A
    fi
  - bundle exec rake docs
