language: ruby
rvm:
  - 2.3.0
before_install:
  - gem update --system
  - gem install bundler
script:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; bundle exec rspec -f d -b; fi
  - bundle exec rubocop -f c --fail-level A
